export const TERMS_MARKDOWN = `# Terms of Service — PharmaIP Radar

**Last updated:** 2026-06-06

By accessing or using PharmaIP Radar ("the Service"), you agree to be bound by these Terms.

## 1. Eligibility

You must be at least 18 years old and have the legal authority to enter into a contract. By using the Service on behalf of an organization, you represent that you have authority to bind that organization.

## 2. Acceptable Use

You agree NOT to:
- Reverse-engineer, decompile, or attempt to extract source code
- Use the Service to build a competing product
- Upload content that infringes third-party IP (or claim to)
- Use the Service for any illegal purpose
- Circumvent rate limits, authentication, or access controls
- Resell or sublicense access without written permission
- Scrape, crawl, or systematically download patent data via the Service
- Use the Service to provide legal advice to third parties (you may use it for your own legal research)

## 3. Service Tiers & Payment

| Tier | Price | Includes |
|---|---|---|
| Starter | $999/mo | 5,000 patent searches, 3 landscapes, 1 watchlist |
| Pro | $2,499/mo | 50,000 searches, unlimited landscapes, 10 watchlists |
| Enterprise | $4,999+/mo | Custom volume, SSO, dedicated CSM |

- All fees in USD, exclusive of taxes
- Monthly billing on the 1st; annual = 2 months free
- Failed payments retry automatically; service suspends after 14 days
- No refunds for partial months. Annual plans refund pro-rata with 30-day notice

## 4. Intellectual Property

**Your data** — You retain all rights to the patent claims, landscapes, and reports you upload or create.

**The Service** — We retain all rights to the platform, algorithms, models, UI, and documentation. We grant you a non-exclusive, non-transferable license to use the Service during your subscription term.

**Generated reports** — Reports generated by the Service are yours. You may use them for your own legal, business, or research purposes.

**Feedback** — If you provide feedback, you grant us a non-exclusive, royalty-free, perpetual license to use it for improvement purposes.

## 5. Disclaimers

THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE DO NOT WARRANT THAT:
- Patent infringement detection is 100% accurate (false positives and false negatives exist)
- The Service will be uninterrupted or error-free
- Results from AI analysis constitute legal advice
- The Service complies with laws of every jurisdiction

**Not legal advice.** The Service is a research and analysis tool. You are responsible for obtaining legal counsel before making decisions based on Service output. AI-generated claim charts and risk scores are starting points for human review, not final determinations.

## 6. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR AGGREGATE LIABILITY FOR ANY CLAIM ARISING FROM OR RELATED TO THE SERVICE IS LIMITED TO THE FEES YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.

IN NO EVENT SHALL WE BE LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS OR LOST DATA.

## 7. Indemnification

You agree to indemnify and hold us harmless from any third-party claim arising from:
- Your use of the Service in violation of these Terms
- Your violation of any law
- Content you upload that infringes third-party rights
- Your breach of confidentiality obligations to your clients

## 8. Termination

- **By you** — Cancel anytime from account settings. Access continues until end of billing period.
- **By us** — We may suspend or terminate for: (a) non-payment after 14-day grace period, (b) material breach of these Terms, (c) illegal use. We will provide 30 days' notice for non-breach terminations.
- **Effect** — Upon termination, your data is retained for 30 days, then permanently deleted. You may export your data during this grace period.

## 9. Confidentiality

We will treat your uploaded patent claims, client data, and analysis as confidential. We will not disclose to third parties except: (a) with your written consent, (b) to comply with law, (c) to our subprocessors under equivalent confidentiality obligations.

You agree to keep your API keys, account credentials, and any non-public Service information confidential.

## 10. Service Level Agreement (Pro & Enterprise)

- 99.5% uptime for Pro tier
- 99.9% uptime for Enterprise tier
- Service credits for downtime exceeding SLA: 5% of monthly fee per hour of downtime, capped at 100% of monthly fee
- Excludes: scheduled maintenance, force majeure, third-party outages

## 11. Governing Law & Disputes

These Terms are governed by the laws of [Your State/Country]. Any dispute will be resolved by binding arbitration in [Your City]. You waive the right to participate in class actions.

## 12. Changes to Terms

We will notify you at least 30 days before material changes. If you do not agree, you may cancel before the effective date.

## 13. Contact

- Email: legal@pharmaip-radar.com
- Support: support@pharmaip-radar.com
- Address: [Your registered business address]`;
