"use client";
// QuantaLab scenario: a 2-person quant shop onboarding a systematic strategy
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Code2, FlaskConical, ShoppingCart, ArrowRight, Building2, CheckCircle2, TrendingUp } from "lucide-react";
import Link from "next/link";

export function Scenario() {
  return (
    <section id="scenario" className="py-20 md:py-32 bg-bg-elevated/30">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-xs font-medium mb-4">
            <Building2 className="h-3.5 w-3.5" />
            Real case study · Apex Research · 2-person quant shop
          </div>
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            From idea to <span className="text-accent">out-of-sample Sharpe 1.87</span> in 4 hours.
          </h2>
          <p className="text-xl text-text-muted">
            Apex Research is a 2-person systematic shop. They had a hunch about overnight-edge strategies on SPY. With QuantaLab, they validated, refined, backtested, and listed it on the marketplace in one afternoon.
          </p>
        </div>

        <div className="max-w-5xl mx-auto space-y-6">
          {/* Step 1 */}
          <Card className="p-6 md:p-8 hover:border-accent/50 transition-colors">
            <div className="grid md:grid-cols-[auto,1fr,auto] gap-6 items-start">
              <div className="flex flex-col items-center gap-2 shrink-0">
                <div className="h-12 w-12 rounded-full bg-gradient-accent flex items-center justify-center text-white font-bold">1</div>
                <ArrowRight className="h-5 w-5 text-text-muted hidden md:block" />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Code2 className="h-5 w-5 text-accent" />
                  <h3 className="text-2xl font-semibold">Describe the strategy in plain English</h3>
                </div>
                <p className="text-text-muted mb-4">
                  Apex types into QuantaLab's NL→Code cell: <em>"Buy SPY at close if overnight gap is negative and 5-day realized vol is below median. Sell at next open. Size at 2% of equity."</em> QuantaLab's local Ollama (qwen3:8b) translates this to executable Python in 4 seconds.
                </p>
                <div className="rounded-lg border border-border bg-bg p-4 font-mono text-xs">
                  <div className="text-text-muted"># Generated by QuantaLab NL→Code (qwen3:8b)</div>
                  <div className="mt-1 text-accent">def signals(prices, vol):</div>
                  <div className="pl-4">gap = prices.open / prices.close.shift(1) - 1</div>
                  <div className="pl-4">vol_5d = prices.close.pct_change().rolling(5).std()</div>
                  <div className="pl-4">if gap &lt; 0 and vol_5d.iloc[-1] &lt; vol.median():</div>
                  <div className="pl-8 text-green-400">return "buy"  # size = 0.02 * equity</div>
                </div>
              </div>
              <div className="hidden md:block text-text-muted text-sm">~ 4 sec vs 2 days</div>
            </div>
          </Card>

          {/* Step 2 */}
          <Card className="p-6 md:p-8 hover:border-accent/50 transition-colors">
            <div className="grid md:grid-cols-[auto,1fr,auto] gap-6 items-start">
              <div className="flex flex-col items-center gap-2 shrink-0">
                <div className="h-12 w-12 rounded-full bg-gradient-accent flex items-center justify-center text-white font-bold">2</div>
                <ArrowRight className="h-5 w-5 text-text-muted hidden md:block" />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <FlaskConical className="h-5 w-5 text-accent" />
                  <h3 className="text-2xl font-semibold">Walk-forward + Monte Carlo in sandboxed notebook</h3>
                </div>
                <p className="text-text-muted mb-4">
                  Apex runs walk-forward validation (2015-2020 train, 2021-2024 test). 5,000-path Monte Carlo stress test (2008 GFC, COVID crash, 2022 bear). Code runs in a sandboxed Python kernel — no server access, no internet. The notebook shows the equity curve fan, the worst drawdown, and the 95% confidence interval.
                </p>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  <div className="rounded-lg border border-border bg-bg p-3"><div className="text-lg font-bold text-accent">1.87</div><div className="text-xs text-text-muted">Out-of-sample Sharpe</div></div>
                  <div className="rounded-lg border border-border bg-bg p-3"><div className="text-lg font-bold text-accent">-8.4%</div><div className="text-xs text-text-muted">Worst drawdown</div></div>
                  <div className="rounded-lg border border-border bg-bg p-3"><div className="text-lg font-bold text-accent">+34.2%</div><div className="text-xs text-text-muted">3-yr out-of-sample return</div></div>
                  <div className="rounded-lg border border-border bg-bg p-3"><div className="text-lg font-bold text-accent">5,000</div><div className="text-xs text-text-muted">Monte Carlo paths</div></div>
                </div>
              </div>
              <div className="hidden md:block text-text-muted text-sm">~ 1 hour vs 2 weeks</div>
            </div>
          </Card>

          {/* Step 3 */}
          <Card className="p-6 md:p-8 hover:border-accent/50 transition-colors">
            <div className="grid md:grid-cols-[auto,1fr,auto] gap-6 items-start">
              <div className="flex flex-col items-center gap-2 shrink-0">
                <div className="h-12 w-12 rounded-full bg-gradient-accent flex items-center justify-center text-white font-bold">3</div>
              </div>
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <ShoppingCart className="h-5 w-5 text-accent" />
                  <h3 className="text-2xl font-semibold">List on the marketplace, earn passive income</h3>
                </div>
                <p className="text-text-muted mb-4">
                  Apex publishes "Overnight Edge Pro" to the QuantaLab marketplace at $49/license. 1,823 quant subscribers buy it in 4 months. Apex earns $44,800 in passive revenue. The marketplace takes 15%. Apex's two-person shop now has a third revenue stream alongside their prop trading and consulting.
                </p>
                <div className="grid md:grid-cols-3 gap-3">
                  <div className="rounded-lg border border-green-500/30 bg-green-500/5 p-3 flex items-center gap-2">
                    <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
                    <span className="text-sm">$89,200 sold in 4 months</span>
                  </div>
                  <div className="rounded-lg border border-green-500/30 bg-green-500/5 p-3 flex items-center gap-2">
                    <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
                    <span className="text-sm">$44,800 net to Apex</span>
                  </div>
                  <div className="rounded-lg border border-green-500/30 bg-green-500/5 p-3 flex items-center gap-2">
                    <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
                    <span className="text-sm">2,400+ new email subscribers</span>
                  </div>
                </div>
              </div>
              <div className="hidden md:block text-text-muted text-sm">~ 5 min</div>
            </div>
          </Card>
        </div>

        <div className="max-w-4xl mx-auto mt-12 text-center">
          <div className="rounded-xl border border-accent/20 bg-gradient-to-br from-accent/5 to-transparent p-8">
            <div className="grid md:grid-cols-3 gap-6 text-left">
              <div>
                <div className="text-3xl font-bold text-accent">1.87</div>
                <div className="text-sm text-text-muted">Out-of-sample Sharpe</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-accent">$44.8k</div>
                <div className="text-sm text-text-muted">Passive revenue in 4 months</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-accent">1,823</div>
                <div className="text-sm text-text-muted">Marketplace subscribers</div>
              </div>
            </div>
            <div className="mt-6">
              <Button asChild size="lg">
                <Link href="/sign-up">Start your first notebook · free</Link>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
